on:
  push:
    branches:
      - main
name: 📟 Deploy Promo Seu Toba FTP Production
defaults:
  run:
    working-directory: ./
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🌎 Sync files to FTP Seu Toba
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 35.198.0.121
          username: promoseutoba.mag3s.com_github
          password: ${{ secrets.PASS_FTP_PROMOSEUTOBA }}
          local-dir: ./
          server-dir: /
          exclude: |
            **/.github/**
            **/.git/**
            **/.vscode/**
            .gitignore
            .editorconfig
            README.md
          dry-run: false

      - name: 🌎 Sync files to FTP PG Influencers
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 35.199.123.44
          username: pginfluencer.mag3s.com_github
          password: ${{ secrets.PASS_FTP_PGINFLUENCERS }}
          local-dir: ./
          server-dir: /
          exclude: |
            **/.github/**
            **/.git/**
            **/.vscode/**
            .gitignore
            .editorconfig
            README.md
          dry-run: false

      - name: 🌎 Sync files to FTP Fiel da Sorte
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 35.199.123.44
          username: tcp.mag3s.com_github
          password: ${{ secrets.PASS_FTP_FIELDASORTE }}
          local-dir: ./
          server-dir: /
          exclude: |
            **/.github/**
            **/.git/**
            **/.vscode/**
            .gitignore
            .editorconfig
            README.md
          dry-run: false

      - name: 🌎 Sync files to FTP Explosao GR6
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 35.199.123.44
          username: explosaogr6.mag3s.com_github
          password: ${{ secrets.PASS_FTP_EXPLOSAOGR6 }}
          local-dir: ./
          server-dir: /
          exclude: |
            **/.github/**
            **/.git/**
            **/.vscode/**
            .gitignore
            .editorconfig
            README.md
          dry-run: false
