on:
  push:
    branches:
      - main
name: 📟 Deploy Fiel da Sorte FTP Production
defaults:
  run:
    working-directory: ./
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🌎 Sync files to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 35.199.123.44
          username: tcp.mag3s.com_github
          password: ${{ secrets.PASS_FTP_FIELDASORTE }}
          local-dir: ./
          server-dir: /
          exclude: |
            **/.github/**
            **/.git/**
            **/.vscode/**
            .gitignore
            .editorconfig
            README.md
          dry-run: false
